## Don't forget to rename this file to "config.ini"
##
## use either email or username and leave the unused as default and the script will ignore
## 
## For streaming in home only set ip = 127.0.0.1 & playlist_host = 127.0.0.1
## Example below is for Tailscale setup
##
[account]
email = example@example.com
username = example
password = password123

[settings]
ip = 0.0.0.0
port = 8888
playlist_host = 100.x.x.x
playlist_scheme = https
playlist_port =
playlist_output = /app/output/siriusxm.m3u
xtra_queue_tracks = 3
xtra_extend_threshold = 0.70
xtra_playlist_max_age = 21600
xtra_session_ttl = 25200
