## Don't forget to rename this file to "config.ini"
##
## use either email or username and leave the unused as default and the script will ignore
## 
## For streaming in home only set ip = 127.0.0.1 & playlist_host = 127.0.0.1
## Example below is for Tailscale setup
##
[account]
email = example@example.com
username = example
password = password123

[settings]
ip = 0.0.0.0
port = 8888
playlist_host = 100.x.x.x
